Diagrama Entidad Relacion
RobertoCarMed/PedidosCol pull request #6
Opened 2021-10-14 19:34 UTC by RobertoCarMed

Se añadio una imagen en formato jpg en donde se plasma el diagrama entidad relacion que se debe seguir para la base de datos.

Este diagrama tiene la finalidad de servir como guia al momento de estar creando las entidades dentro de la base de datos

resolve #2

2021-10-14 20:11 UTC, CUBOFIG approved these changes
LGTM

2021-10-14 20:23 UTC, xFerchoVJ commented
Puedes poner una foto en la descripción del PR para ver el diagrama?

2021-10-14 20:38 UTC, xFerchoVJ approved these changes
LGTM

2021-10-14 20:44 UTC, xFerchoVJ requested changes
Agregar el campo Imagen para las entidades que la requieran.

2021-10-18 18:31 UTC, xFerchoVJ approved these changes
LGTM

2021-10-18 18:31 UTC, merged